name: first-github-actions
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: commands
        run: echo "hello world"
  test2:
    runs-on: ubuntu-latest
    steps:
      - name: commands
        run: echo "hello world1"
     
